package com.lirs.bysj.pojo;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ui_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private Integer uiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ui_rname
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private String uiRname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ui_adress
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private String uiAdress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ui_phone
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private String uiPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.ui_score
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private Integer uiScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.u_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private Integer uId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ui_id
     *
     * @return the value of userinfo.ui_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public Integer getUiId() {
        return uiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ui_id
     *
     * @param uiId the value for userinfo.ui_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setUiId(Integer uiId) {
        this.uiId = uiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ui_rname
     *
     * @return the value of userinfo.ui_rname
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public String getUiRname() {
        return uiRname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ui_rname
     *
     * @param uiRname the value for userinfo.ui_rname
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setUiRname(String uiRname) {
        this.uiRname = uiRname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ui_adress
     *
     * @return the value of userinfo.ui_adress
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public String getUiAdress() {
        return uiAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ui_adress
     *
     * @param uiAdress the value for userinfo.ui_adress
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setUiAdress(String uiAdress) {
        this.uiAdress = uiAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ui_phone
     *
     * @return the value of userinfo.ui_phone
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public String getUiPhone() {
        return uiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ui_phone
     *
     * @param uiPhone the value for userinfo.ui_phone
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setUiPhone(String uiPhone) {
        this.uiPhone = uiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.ui_score
     *
     * @return the value of userinfo.ui_score
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public Integer getUiScore() {
        return uiScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.ui_score
     *
     * @param uiScore the value for userinfo.ui_score
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setUiScore(Integer uiScore) {
        this.uiScore = uiScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.u_id
     *
     * @return the value of userinfo.u_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.u_id
     *
     * @param uId the value for userinfo.u_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }
}