package com.lirs.bysj.pojo;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private Integer uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.usernumber
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private Integer usernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userpwd
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.time
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.usernumber
     *
     * @return the value of user.usernumber
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public Integer getUsernumber() {
        return usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.usernumber
     *
     * @param usernumber the value for user.usernumber
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setUsernumber(Integer usernumber) {
        this.usernumber = usernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userpwd
     *
     * @return the value of user.userpwd
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userpwd
     *
     * @param userpwd the value for user.userpwd
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.time
     *
     * @return the value of user.time
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.time
     *
     * @param time the value for user.time
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}