package com.lirs.bysj.MapperDao;

import java.util.List;

import com.lirs.bysj.pojo.User;


public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Tue Jul 18 16:38:31 CST 2017
     */
    int deleteByPrimaryKey(Integer uId);
    
    List<User> selectAll();

    int insert(User record);

    int insertSelective(User record);

    User selectByPrimaryKey(Integer uId);

    int updateByPrimaryKeySelective(User record);
   
    int updateByPrimaryKey(User record);
    
    /**
     * 查询所有数据，分页时用到这个
     * @return
     */
    List<User> selectUserList();
}